// Event Name

export const CHAT_EVENTS = {
  ALERT: 'ALERT',
  REFETCH: 'REFETCH',
  MESSAGE: 'MESSAGE',
};

export const MESSAGE_EVENTS = {
  NEW_MESSAGE: 'NEW_MESSAGE',
  SENT: 'MESSAGE_SENT',
  RECEIVED: 'MESSAGE_RECEIVED',
  DELIVERED: 'MESSAGE_DELIVERED',
  READ: 'MESSAGE_READ',
};

export const ATTACHMENT_EVENTS = {
  NEW_ATTACHMENT: 'NEW_ATTACHMENT',
  REMOVE: 'ATTACHMENT_REMOVE',
};

export const REQUEST_EVENTS = {
  NEW_REQUEST: 'NEW_REQUEST',
  REQUEST_ACCEPTED: 'REQUEST_ACCEPTED',
  REQUEST_DECLINE: 'REQUEST_DECLINE',
};
