
networks:
  chat-app-network:
    driver: bridge

volumes:
  mongo_data:

services:

  mongo:
    image: mongo:6
    restart: always
    ports: 
      - 27017
    volumes:
      - mongo_data:/data/db
    networks:
      - chat-app-network

  backend:
    build: ./server
    container_name: chat-app-backend
    ports: 
      - 3100
    depends_on: 
      - mongo
    networks: 
      - chat-app-network
    restart: unless-stopped
  
  frontend:
    build: ./client
    container_name: chat-app-frontend
    ports: 
      - 5173
    depends_on:
      - backend
    networks:
      - chat-app-network
    restart: unless-stoped
